export const strings = {
  restaurents: "396 restaurants around you",
  max_safety: "MAX SAFETY",
  dilvery: "DILVERY",
  eat_what: "Eat what makes you happy",
  location: "Kukatpally, Hyderabad",
  six: "6",
  photo: "PHOTO",
  distanceText: " distance charge",
  recommended: "Recommended",
  menu: "Menu",
  off_upto: "OFF up to",
  use_code_text: "Use code ZOMSAFETY on orders with items worth ",
  or_more: "or more",
  dinig: "DINING",
  reviews: "REVIEWS",
  full_name: "Full Menu",
  healthy: "Healthy",
  veg:'Veg',
  egg:'Egg',
  must_try:'Must Try',
  add:'ADD',
  see_more:'read more',
  read_less:'read less',
};
